phrase:
  access_token: 1731b3e2cdb8eeac119ec6c66f7c2b6f6eb839a1d3dbb40b140627f942f0d836
  project_id: 569305065a9b342f3e67ee5ff0e6f468
  push:
    sources:
    - file: ./resources/lang/en/notifications.php
      params:
        locale_id: en
        file_format: laravel
    - file: ./resources/lang/es/notifications.php
      params:
        locale_id: es
        file_format: laravel
    - file: ./resources/lang/fr/notifications.php
      params:
        locale_id: fr
        file_format: laravel
    - file: ./resources/lang/en/api.php
      params:
        locale_id: en
        file_format: laravel
    - file: ./resources/lang/es/api.php
      params:
        locale_id: es
        file_format: laravel
    - file: ./resources/lang/fr/api.php
      params:
        locale_id: fr
        file_format: laravel

  pull:
    targets:
    - file: ./resources/lang/en/notifications.php
      params:
        locale_id: en
        file_format: laravel
    - file: ./resources/lang/es/notifications.php
      params:
        locale_id: es
        file_format: laravel
    - file: ./resources/lang/fr/notifications.php
      params:
        locale_id: fr
        file_format: laravel
    - file: ./resources/lang/en/api.php
      params:
        locale_id: en
        file_format: laravel
    - file: ./resources/lang/es/api.php
      params:
        locale_id: es
        file_format: laravel
    - file: ./resources/lang/fr/api.php
      params:
        locale_id: fr
        file_format: laravel
